packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^22.17.0
  typescript: ^5.9.2
  vitest: ^3.2.4

catalogs:
  react:
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1
    react-router: ^7
  rspack:
    '@rsbuild/core': ~1.4.14
    '@rsbuild/plugin-less': ^1.3.2
    '@rsbuild/plugin-react': ^1.3.5
    '@rsbuild/plugin-svgr': ^1.2.2
    '@rslib/core': ~0.11.2
  storybook:
    '@storybook/addon-essentials': ^8.6.14
    '@storybook/addon-interactions': ^8.6.14
    '@storybook/addon-links': ^8.6.14
    '@storybook/addon-onboarding': ^8.6.14
    '@storybook/blocks': ^8.6.14
    '@storybook/react': ^8.6.14
    '@storybook/test': ^8.6.14
    storybook: ^8.6.14
    storybook-addon-rslib: ^1.0.2
    storybook-react-rsbuild: ^1.0.2
